* Story of the short weevil

Being a weevil is hard. You are small, always hungry and always on a lookout for predators.
You mght think that you are safe, and then you look up and see yet another pidgeon circling around.
Pindgeons are fortunately not that smart. Especially the ones livint in the city.
Weevil looks to the sky. Remembers the time when he rode a pidgeon. Pidgeon probably didn't even notice.
It was one of the pretty ones. Probably lived in the forest. Not the dirty city. And weevil looked up to the sky,
wanting to fly again.

* there is a man, watching this world.. Sometimes  intervening. Wrong man in the right plqce can make all the difference.

Should look into the controll/scp/warehouse13.

* Mr. Scurlock

so, where were we? No, I am not *that* scurlock. I do know my fair share of whispers and sparkwritghts, but I have no access to the seats of power my name-sake seems to flount so much.

But if you need a leech or a tinker, or maybe even a witch, I could ask a friend if they know of a friend. There always is soomebody willing to sell their soul for a coin. Well, if they still have a soul. I knew an automaton, once. looked like a human. No spirit in the wesssel, alll electroplasm and clockwork.. 
