* Story of the short weevil

Being a weevil is hard. You are small, always hungry and always on a lookout for predators.
You mght think that you are safe, and then you look up and see yet another pidgeon circling around.
Pindgeons are fortunately not that smart. Especially the ones livint in the city.
Weevil looks to the sky. Remembers the time when he rode a pidgeon. Pidgeon probably didn't even notice.
It was one of the pretty ones. Probably lived in the forest. Not the dirty city. And weevil looked up to the sky,
wanting to fly again.

* there is a man, watching this world.. Sometimes  intervening. Wrong man in the right plqce can make all the difference.

Should look into the controll/scp/warehouse13.

* Mr. Scurlock

so, where were we? No, I am not *that* scurlock. I do know my fair share of whispers and sparkwritghts, but I have no access to the seats of power my name-sake seems to flount so much.

But if you need a leech or a tinker, or maybe even a witch, I could ask a friend if they know of a friend. There always is soomebody willing to sell their soul for a coin. Well, if they still have a soul. I knew an automaton, once. looked like a human. No spirit in the wesssel, alll electroplasm and clockwork.. 

* short stories

Mice qotient:
4 elements: milieu, inquiry, character, event
milieu: entering and exiting space - i.e. gulivers travels
 - conflict is abbout dificulty in navigating to the exit
inqury: question -> answer - i.e. sherlock holmes
 - conflict is about not finding answers and red herrings
character: unhappy -> happy? ... identity shift
 - conflict: stop hem from chnging
event: external disruption of status-qo -> new status quo
 - don't let them fix it

Character - interior
Event - exterior
Multi threaded story:
<m><i></i></m>

Opening -> who - action, where - sensory detail, genre in first 3 sentences
Assignment - Genre - Scify, Who - Jockey, What - coaster

Conflict - yes, but/ no, and
Resolution - yes, and ()/ no, but (couldn't defuse the bomb, but the building got evacuated)

Character shorthand - i.e. teenage jockey

Jockey grabbed one of those weighlessly floating coasters right before she turned the gravity back on in the club, just as she dropped the base. The crowd cheers. 
Except the one man that keeps staring at her. What is he doing there. She tries not to get distracted by that. Show must go on. Next song, slowly graduates, people lift their hands,
Jockey slowly lowers the gravity, as everybody starts to float. She might have a minute before the next bit, so she kicks herself off the pult and floats through the crowd closer to the man subbornly standing on the floor in mirror shades. She doesn't recognize him. And now she is weightless in the middle of the room full of floating clubbers with just half a minute to somehow get back to her pult. She grabs one of the clubbers, smiles at them, does a weird somersault and pushes them away. This
makes them float in the oposite directions and she lands back.
