* Story of the short weevil

Being a weevil is hard. You are small, always hungry and always on a lookout for predators.
You mght think that you are safe, and then you look up and see yet another pidgeon circling around.
Pindgeons are fortunately not that smart. Especially the ones livint in the city.
Weevil looks to the sky. Remembers the time when he rode a pidgeon. Pidgeon probably didn't even notice.
It was one of the pretty ones. Probably lived in the forest. Not the dirty city. And weevil looked up to the sky,
wanting to fly again.

* there is a man, watching this world.. Sometimes  intervening. Wrong man in the right plqce can make all the difference.

Should look into the controll/scp/warehouse13.

* Mr. Scurlock

so, where were we? No, I am not *that* scurlock. I do know my fair share of whispers and sparkwritghts, but I have no access to the seats of power my name-sake seems to flount so much.

But if you need a leech or a tinker, or maybe even a witch, I could ask a friend if they know of a friend. There always is soomebody willing to sell their soul for a coin. Well, if they still have a soul. I knew an automaton, once. looked like a human. No spirit in the wesssel, alll electroplasm and clockwork.. 

* short stories

Mice qotient:
4 elements: milieu, inquiry, character, event
milieu: entering and exiting space - i.e. gulivers travels
 - conflict is abbout dificulty in navigating to the exit
inqury: question -> answer - i.e. sherlock holmes
 - conflict is about not finding answers and red herrings
character: unhappy -> happy? ... identity shift
 - conflict: stop hem from chnging
event: external disruption of status-qo -> new status quo
 - don't let them fix it

Character - interior
Event - exterior
Multi threaded story:
<m><i></i></m>

Opening -> who - action, where - sensory detail, genre in first 3 sentences
Assignment - Genre - Scify, Who - Jockey, What - coaster

Conflict - yes, but/ no, and
Resolution - yes, and ()/ no, but (couldn't defuse the bomb, but the building got evacuated)

Character shorthand - i.e. teenage jockey

Jockey grabbed one of those weighlessly floating coasters right before she turned the gravity back on in the club, just as she dropped the base. The crowd cheers. 
Except the one man that keeps staring at her. What is he doing there. She tries not to get distracted by that. Show must go on. Next song, slowly graduates, people lift their hands,
Jockey slowly lowers the gravity, as everybody starts to float. She might have a minute before the next bit, so she kicks herself off the pult and floats through the crowd closer to the man subbornly standing on the floor in mirror shades. She doesn't recognize him. And now she is weightless in the middle of the room full of floating clubbers with just half a minute to somehow get back to her pult. She grabs one of the clubbers, smiles at them, does a weird somersault and pushes them away. This
makes them float in the oposite directions and she lands back.

3 minutes - First 3 sentences - Who - with action, where - with sensory information, genre - specific and unique.  
2 minutes - Two sentences - What and Why are doing? Why it fails/What is stopping them? 
5 minutes - Five sentences - Try/fail, either "yes, but" or "no and"
5 minutes - Five sentences - Try/succeed, either "no, but" or "yes, and"
3 minutes - 3 sentences - Ending, Who, Where, Genre? - mirror the opening

* Maushexe
** Who/where/genre?
"Graveyards during rain are strangely peaceful",
the little mouse thought to herself,
as she cradled the ancient spell tablet in her paws.
** What/why?
Recharging of the spell would take most of the night,
and it was her turn to stand guard.
** Try/fail - yes,but/no,and
1. The spirit of the first beetle have woken up before midnight,
2. compeled by the power of the tablet made to bind it to servitude.
3. But the tablet was thin and brittle, and some cracks already started to showing.
4. The spirit beetle shrieked, and the crack in the tablet grew longer.
5. She needed to do somethng before she ends up with two halves of a broken spell
** Try/succeed - yes,and/no,but
1. She searches her pouch, there is a piece of string, chalk, charcoal, a focusing crystal, all seem useless.
4. She remembers they did use salt to keep bad spirits out of their homes, maybe it will hold a spirit inside.
5. Finds her salt pouch and tries to quickly circle around the spirit beetle, leaving a salt trail behind her.
4. Beetle tries to knock her back, but the salt seems to be working its magic.
5. After few tries, the tired spirit lays onto the ground, translucent, but visible.
** Ending, Who/Where/Genre - mirror opening
1. There was peace in the graveyard again.
2. Despite the cracked tablet, she still managed to catch that spirit.
3. And her mentor woll have to deal wit the fact she used some unorthodox methods.

* The hound

In secluded corner of Rowans House, Morriston Templeton shuffles a deck of cards.
His mark, a young acolyte, just entered. One of them was about to walk out with a loaded spirit bottle,
and it was important it wasn't the cult that wronged him. 

He surveyed the room and noticed no whispers.
That seemed odd, in a city, where a spirit of a murder victim could avenge her death if left unchecked. 
The seller was in the opposite corner. He should approach them before they make the trade.

As he nears the table, a burly man stands up to intercept: "Mr. Volaris doesn't want t be disturbed". 
He didn't anticipate bodyguard this big. Moriston was used to being the most intimidating man in the room. Maybe this really was above his paygrade.

Volaris looks up at Templeton and then back at the acolyte: "Are we expecting someone?"
Moriston jumps at the opportunity and shouts: "The church sent me to help escort the initiate 
and the precious cargo" and he holds up the polstered briefcase to give his words some heft.
Volaris frowns. "We agreed you come in alone,the deal is off". 
The acolyte looks puzzled: "At least show me you have the cargo, church will then surely arrange 
a new meeting without interfernce"

Volaris opens his briefcase. The bottle was there. Templeton could feel the rage of the spirit trapped in there. 
It was her. Focused, attuned to the spirit and pushed as much energy he could into the ghost field. 
The bottle started to crack. "You madman, what are you doing?", shouts.
The bodyguard realized too late what was happening and even though he knocked Morris out out in a single swing
the spirit was already out. She was free to avenge herself.

* Above a crumbling mansion house, Sevoy Mitcher studies a map.
The old man should be in his bedroom by now. He retained just a single butler,
and they keep to the last three rooms that are not in complete disrepair yet.
But underneath the mansion there is still the valut.

Climbing down and not waking anybody was easy enough. But valuts lock mechanism stumped him.
He was used to elaborate finely crafted keys, or mechanical combinations, even some of the fancy new electroplasmic stuff. Glowing runes though? But the family was old, so ocult precautions are not that out of the ordinary. He had a special hammer for such ocasions. So he got to work and started wrecking. Sevoy didn't really care what weird rituals gave the hammer its power, just that despite its small size, it shattered the runes one by one with ease.

With each stone shattered, the room grew just a tiny bit colder. There was a whisper in the back of his mind that grew tiny bit stronger. By the last rune it was no longer just a whisper but a audible voice.

* The quack of quedlynburd

There she comes, the small mause standing in front of the dreaded cat lord balthazar,
in the large hall where he convenes his court. Her pocker full of components at her side.

"So, you want an audience. You shall have it. speak"

"I came here to bargain, balathazar. I can give you knowledge of a powerful spell, if you provide me safe pasage to the heartland"
